font_family      FiraCode Nerd Font

cursor_blink_interval 0

url_style straight

open_url_with firefox

detect_urls yes

underline_hyperlinks always

# shift-enter and control-enter
map shift+enter send_text all \x1b[13;2u
map ctrl+enter send_text all \x1b[13;5u
